version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"


  mysql:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'emotion_recognizer'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./backend/uploads/media:/var/lib/mysql-files

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    depends_on:
      - mysql